/**
 * This file was automatically generated by npm_scripts/i18n:type.js.
 * DO NOT MODIFY IT BY HAND.
 */

export type SupportedLanguage =
	| "it"
	| "en"

export type Namespace =
	| "common"
	| "filters"
	| "index"
	| "login"
	| "pagination"
	| "select"
	| "signup"

export type Route =
	|  "/"
	| "/login"
	| "/signup"
	| "/confirmEmail"
