/**
 * This file was automatically generated by npm_scripts/icons:type.js.
 * DO NOT MODIFY IT BY HAND.
 */

export type IconName =
	| "alert-circle"
	| "arrow-left"
	| "arrow-right"
	| "caret-down"
	| "caret-up"
	| "chevron-left"
	| "chevron-right"
	| "eye-off"
	| "letters-case"
	| "logo"
	| "plus"
	| "search"
	| "x"