/* eslint-disable no-console */
const { readdirSync, writeFileSync } = require("fs")
const { join } = require("path")

const assetsDir = join(process.cwd(), "public/assets/icons")
const typesFile = join(process.cwd(), "src/types/icon.d.ts")

const icons = readdirSync(assetsDir)
const separator = "\n\t"

const names = []
icons.forEach(filename => {
  if (filename.endsWith(".svg")) {
    names.push(filename.replace(".svg", ""))
  }
})
let out = `/**
 * This file was automatically generated by npm_scripts/icons:type.js.
 * DO NOT MODIFY IT BY HAND.
 */\n\n`
out += `export type IconName =${separator}| ${names.map(name => `"${name}"`).join(`${separator}| `)}`

writeFileSync(typesFile, out)
console.log("Icons type generated successfully")
